# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-04 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
