# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-04 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(default='', max_length=300)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
